--ESEMPIO DI CREAZIONE DI TABELLA

--CREATE TABLE NOME_TABELLA (
--	SCRITTURA ATTRIBUTI
--	nome VARCHAR(50), cognome VARCHAR(50)	);

	-- INSERIMENTO VALORI ALL'INTERNO DEGLI ATTRIBUTI
--INSERT INTO NOME_TABELLA VALUES ('Ismail','Sifdine');

	-- INSERIMENTO PER CAMBIARE L'ORDINE DI INSERIMENTO DEI VALORI
--INSERT INTO NOME_TABELLA (cognome, nome) VALUES ('Yasmine','Fathallah');


--SELECT * FROM NOME_TABELLA;--> vedere quello che c'è nella tabella

--TRUNCATE table NOME_TABELLA;--  -> ELIMINA I DATI DA UNA TABELLA
--DROP table NOME_TABELLA -- -> ELIMINA UNA TABELLA DA UN SERVER

--INSERT INTO studente (matricola, cognome) VALUES (129, 'SIFDINE')

/*CREATE TABLE STUDENTE (
		matr INTEGER PRIMARY KEY,
		nome varchar(10) NOT NULL,
		mail varchar (20)
)

CREATE TABLE DOCENTE(
		CF varchar(16) PRIMARY KEY,
		NOME VARCHAR(10) NOT NULL
)

CREATE TABLE CORSO (
		codice varchar(12) PRIMARY KEY,
		denom varchar(22) NOT NULL
)

CREATE TABLE ESAME (
		matr integer REFERENCES STUDENTE,
		codice varchar(12) REFERENCES CORSO,
		voto INTEGER NOT NULL,
		PRIMARY KEY (matr, codice)
)

CREATE TABLE DOCENZA(
		CODICE VARCHAR(12) PRIMARY KEY REFERENCES CORSO,
		CFdocente varchar(16) REFERENCES DOCENTE NOT NULL
)



SELECT * FROM studente;
*/

--INSERT INTO ISMA VALUES (563, 'NON MOLLAR', 110)
--SELECT * FROM ISMA;
